/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Aluno;

/**
 *
 * @author Aluno
 */
public class UICadAluno extends javax.swing.JFrame {

    Aluno a = new Aluno();

    /**
     * @author Henrique Peixoto & Anderson Justo
     * @since 28/06/17 16:16
     * @version 1.0 batatonha
     */
    public UICadAluno() {
        initComponents();
        jtNome.grabFocus();
        jbRelatorio.setEnabled(false);
        jrMasculino.setSelected(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jlpTudo = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlSexo = new javax.swing.JLabel();
        jlNomeErro = new javax.swing.JLabel();
        jrMasculino = new javax.swing.JRadioButton();
        jrFeminino = new javax.swing.JRadioButton();
        jlIdade = new javax.swing.JLabel();
        jtIdade = new javax.swing.JTextField();
        jlDiscCusr = new javax.swing.JLabel();
        jlpDiscCurs = new javax.swing.JLayeredPane();
        jcSO1 = new javax.swing.JCheckBox();
        jcPHP = new javax.swing.JCheckBox();
        jcJava = new javax.swing.JCheckBox();
        jcAndroid = new javax.swing.JCheckBox();
        jlpNotas = new javax.swing.JLayeredPane();
        jlNota1 = new javax.swing.JLabel();
        jtNota1 = new javax.swing.JTextField();
        jlNota2 = new javax.swing.JLabel();
        jtNota2 = new javax.swing.JTextField();
        jlPeso1 = new javax.swing.JLabel();
        jlPeso2 = new javax.swing.JLabel();
        jtPeso1 = new javax.swing.JTextField();
        jtPeso2 = new javax.swing.JTextField();
        jlTotalAulas = new javax.swing.JLabel();
        jtTotalAulas = new javax.swing.JTextField();
        jlNumPresenca = new javax.swing.JLabel();
        jtNumPresenca = new javax.swing.JTextField();
        jlNota1Erro = new javax.swing.JLabel();
        jlNota2Erro = new javax.swing.JLabel();
        jlTotalAulasErro = new javax.swing.JLabel();
        jlPeso1Erro = new javax.swing.JLabel();
        jlPeso2Erro = new javax.swing.JLabel();
        jlNumPresencaErro = new javax.swing.JLabel();
        jlIdadeErro = new javax.swing.JLabel();
        jlSexoErro = new javax.swing.JLabel();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlpTudo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jlSexo.setText("Sexo");

        bgSexo.add(jrMasculino);
        jrMasculino.setText("Masculino");
        jrMasculino.setActionCommand("masculino");
        jrMasculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrMasculinoKeyPressed(evt);
            }
        });

        bgSexo.add(jrFeminino);
        jrFeminino.setText("Feminino");
        jrFeminino.setActionCommand("feminino");
        jrFeminino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jrFemininoFocusLost(evt);
            }
        });
        jrFeminino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrFemininoKeyPressed(evt);
            }
        });

        jlIdade.setText("Idade");

        jtIdade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtIdadeFocusLost(evt);
            }
        });
        jtIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtIdadeKeyPressed(evt);
            }
        });

        jlDiscCusr.setText("Disciplinas cursadas");

        jlpDiscCurs.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jcSO1.setText("SO1");
        jcSO1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcSO1KeyPressed(evt);
            }
        });

        jcPHP.setText("PHP");
        jcPHP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcPHPKeyPressed(evt);
            }
        });

        jcJava.setText("Java");
        jcJava.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcJavaKeyPressed(evt);
            }
        });

        jcAndroid.setText("Android");
        jcAndroid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcAndroidKeyPressed(evt);
            }
        });

        jlpDiscCurs.setLayer(jcSO1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDiscCurs.setLayer(jcPHP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDiscCurs.setLayer(jcJava, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDiscCurs.setLayer(jcAndroid, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDiscCursLayout = new javax.swing.GroupLayout(jlpDiscCurs);
        jlpDiscCurs.setLayout(jlpDiscCursLayout);
        jlpDiscCursLayout.setHorizontalGroup(
            jlpDiscCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDiscCursLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jlpDiscCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcSO1)
                    .addComponent(jcJava))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jlpDiscCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcPHP)
                    .addComponent(jcAndroid))
                .addGap(20, 20, 20))
        );
        jlpDiscCursLayout.setVerticalGroup(
            jlpDiscCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDiscCursLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpDiscCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcSO1)
                    .addComponent(jcPHP))
                .addGap(18, 18, 18)
                .addGroup(jlpDiscCursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcJava)
                    .addComponent(jcAndroid))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlpNotas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNota1.setText("Nota 1");

        jtNota1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNota1FocusLost(evt);
            }
        });
        jtNota1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNota1KeyPressed(evt);
            }
        });

        jlNota2.setText("Nota 2");

        jtNota2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNota2FocusLost(evt);
            }
        });
        jtNota2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNota2KeyPressed(evt);
            }
        });

        jlPeso1.setText("Peso 1");

        jlPeso2.setText("Peso 2");

        jtPeso1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPeso1FocusLost(evt);
            }
        });
        jtPeso1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPeso1KeyPressed(evt);
            }
        });

        jtPeso2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPeso2FocusLost(evt);
            }
        });
        jtPeso2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPeso2KeyPressed(evt);
            }
        });

        jlTotalAulas.setText("Total de Aulas");

        jtTotalAulas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtTotalAulasFocusLost(evt);
            }
        });
        jtTotalAulas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTotalAulasKeyPressed(evt);
            }
        });

        jlNumPresenca.setText("Num presenças");

        jtNumPresenca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNumPresencaFocusLost(evt);
            }
        });
        jtNumPresenca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNumPresencaKeyPressed(evt);
            }
        });

        jlpNotas.setLayer(jlNota1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jtNota1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jlNota2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jtNota2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jlPeso1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jlPeso2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jtPeso1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jtPeso2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jlTotalAulas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jtTotalAulas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jlNumPresenca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jtNumPresenca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jlNota1Erro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jlNota2Erro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jlTotalAulasErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jlPeso1Erro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jlPeso2Erro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpNotas.setLayer(jlNumPresencaErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpNotasLayout = new javax.swing.GroupLayout(jlpNotas);
        jlpNotas.setLayout(jlpNotasLayout);
        jlpNotasLayout.setHorizontalGroup(
            jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpNotasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jlpNotasLayout.createSequentialGroup()
                        .addComponent(jlNota2)
                        .addGap(18, 18, 18)
                        .addComponent(jtNota2))
                    .addGroup(jlpNotasLayout.createSequentialGroup()
                        .addComponent(jlNota1)
                        .addGap(18, 18, 18)
                        .addComponent(jtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlNota1Erro, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jlNota2Erro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpNotasLayout.createSequentialGroup()
                        .addComponent(jlPeso1)
                        .addGap(34, 34, 34)
                        .addComponent(jtPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpNotasLayout.createSequentialGroup()
                        .addComponent(jlPeso2)
                        .addGap(34, 34, 34)
                        .addComponent(jtPeso2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPeso1Erro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPeso2Erro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpNotasLayout.createSequentialGroup()
                .addComponent(jlTotalAulas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtTotalAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTotalAulasErro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jlNumPresenca)
                .addGap(34, 34, 34)
                .addComponent(jtNumPresenca, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jlNumPresencaErro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jlpNotasLayout.setVerticalGroup(
            jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpNotasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNota1)
                    .addComponent(jlPeso1)
                    .addComponent(jlPeso1Erro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtPeso1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(jtNota1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlNota1Erro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpNotasLayout.createSequentialGroup()
                        .addGroup(jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNota2)
                            .addComponent(jtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addComponent(jlNota2Erro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jlpNotasLayout.createSequentialGroup()
                        .addGroup(jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPeso2)
                            .addComponent(jtPeso2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jlPeso2Erro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpNotasLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlNumPresencaErro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpNotasLayout.createSequentialGroup()
                                    .addGroup(jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlNumPresenca)
                                        .addComponent(jtNumPresenca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(23, 23, 23)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpNotasLayout.createSequentialGroup()
                                .addGroup(jlpNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlTotalAulas)
                                    .addComponent(jtTotalAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21))))
                    .addGroup(jlpNotasLayout.createSequentialGroup()
                        .addComponent(jlTotalAulasErro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jlpTudo.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpTudo.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpTudo.setLayer(jlSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpTudo.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpTudo.setLayer(jrMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpTudo.setLayer(jrFeminino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpTudo.setLayer(jlIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpTudo.setLayer(jtIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpTudo.setLayer(jlDiscCusr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpTudo.setLayer(jlpDiscCurs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpTudo.setLayer(jlpNotas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpTudo.setLayer(jlIdadeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpTudo.setLayer(jlSexoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpTudoLayout = new javax.swing.GroupLayout(jlpTudo);
        jlpTudo.setLayout(jlpTudoLayout);
        jlpTudoLayout.setHorizontalGroup(
            jlpTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpTudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpTudoLayout.createSequentialGroup()
                        .addGroup(jlpTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jlpTudoLayout.createSequentialGroup()
                                .addComponent(jlIdade)
                                .addGap(18, 18, 18)
                                .addComponent(jtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlIdadeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jlpTudoLayout.createSequentialGroup()
                                .addComponent(jlDiscCusr)
                                .addGap(49, 49, 49)
                                .addComponent(jlpDiscCurs)
                                .addGap(112, 112, 112))
                            .addComponent(jlpNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(jlpTudoLayout.createSequentialGroup()
                        .addGroup(jlpTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpTudoLayout.createSequentialGroup()
                                .addComponent(jlNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jlpTudoLayout.createSequentialGroup()
                                .addComponent(jlSexo)
                                .addGap(18, 18, 18)
                                .addComponent(jrMasculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrFeminino)
                                .addGap(18, 18, 18)
                                .addComponent(jlSexoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jlpTudoLayout.setVerticalGroup(
            jlpTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpTudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlSexo)
                        .addComponent(jrMasculino)
                        .addComponent(jrFeminino))
                    .addComponent(jlSexoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdade)
                    .addComponent(jtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlIdadeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jlpTudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpTudoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlpDiscCurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpTudoLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jlDiscCusr)))
                .addGap(38, 38, 38)
                .addComponent(jlpNotas)
                .addGap(4, 4, 4))
        );

        jlpAcoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jbLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparKeyPressed(evt);
            }
        });

        jbRelatorio.setText("Relatorio");
        jbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioActionPerformed(evt);
            }
        });
        jbRelatorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbRelatorioKeyPressed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbRelatorio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jbRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jbRelatorio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlpTudo)
                    .addComponent(jlpAcoes))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpTudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioActionPerformed
        // TODO add your handling code here:
        relatorio();
    }//GEN-LAST:event_jbRelatorioActionPerformed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrMasculino.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jrMasculinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrMasculinoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrFeminino.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jrMasculinoKeyPressed

    private void jrFemininoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrFemininoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtIdade.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jrFemininoKeyPressed

    private void jtIdadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIdadeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcSO1.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jtIdadeKeyPressed

    private void jcSO1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcSO1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcPHP.grabFocus();
        }// fecha if
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            jcJava.grabFocus();
        }// fecha if
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            jcPHP.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jcSO1KeyPressed

    private void jcPHPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcPHPKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcJava.grabFocus();
        }// fecha if
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            jcAndroid.grabFocus();
        }// fecha if
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            jcSO1.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jcPHPKeyPressed

    private void jcJavaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcJavaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jcAndroid.grabFocus();
        }// fecha if
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            jcSO1.grabFocus();
        }// fecha if
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            jcAndroid.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jcJavaKeyPressed

    private void jcAndroidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcAndroidKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtNota1.grabFocus();
        }// fecha if
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            jcJava.grabFocus();
        }// fecha if
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            jcPHP.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jcAndroidKeyPressed

    private void jtNota1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNota1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtNota2.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jtNota1KeyPressed

    private void jtNota2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNota2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtTotalAulas.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jtNota2KeyPressed

    private void jtTotalAulasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTotalAulasKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtPeso1.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jtTotalAulasKeyPressed

    private void jtPeso1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPeso1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtPeso2.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jtPeso1KeyPressed

    private void jtPeso2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPeso2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtNumPresenca.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jtPeso2KeyPressed

    private void jtNumPresencaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNumPresencaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCadastrar.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jtNumPresencaKeyPressed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        // TODO add your handling code here:
        if (jtNome.getText().isEmpty()) {
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtNome.setBorder(BorderFactory.createLineBorder(Color.green));
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtIdadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtIdadeFocusLost
        // TODO add your handling code here:
        if (jtIdade.getText().isEmpty()) {
            jtIdade.setBorder(BorderFactory.createLineBorder(Color.red));
            jlIdadeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtIdade.setBorder(BorderFactory.createLineBorder(Color.green));
            jlIdadeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtIdadeFocusLost

    private void jtNota1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota1FocusLost
        // TODO add your handling code here:
        if (jtNota1.getText().isEmpty()) {
            jtNota1.setBorder(BorderFactory.createLineBorder(Color.red));
            jlNota1Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtNota1.setBorder(BorderFactory.createLineBorder(Color.green));
            jlNota1Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtNota1FocusLost

    private void jtNota2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNota2FocusLost
        // TODO add your handling code here:
        if (jtNota2.getText().isEmpty()) {
            jtNota2.setBorder(BorderFactory.createLineBorder(Color.red));
            jlNota2Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtNota2.setBorder(BorderFactory.createLineBorder(Color.green));
            jlNota2Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtNota2FocusLost

    private void jtPeso1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPeso1FocusLost
        // TODO add your handling code here:
        if (jtPeso1.getText().isEmpty()) {
            jtPeso1.setBorder(BorderFactory.createLineBorder(Color.red));
            jlPeso1Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtPeso1.setBorder(BorderFactory.createLineBorder(Color.green));
            jlPeso1Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtPeso1FocusLost

    private void jtPeso2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPeso2FocusLost
        // TODO add your handling code here:
        if (jtPeso2.getText().isEmpty()) {
            jtPeso2.setBorder(BorderFactory.createLineBorder(Color.red));
            jlPeso2Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtPeso2.setBorder(BorderFactory.createLineBorder(Color.green));
            jlPeso2Erro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtPeso2FocusLost

    private void jtTotalAulasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTotalAulasFocusLost
        // TODO add your handling code here:
        if (jtTotalAulas.getText().isEmpty()) {
            jtTotalAulas.setBorder(BorderFactory.createLineBorder(Color.red));
            jlTotalAulasErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtTotalAulas.setBorder(BorderFactory.createLineBorder(Color.green));
            jlTotalAulasErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtTotalAulasFocusLost

    private void jtNumPresencaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNumPresencaFocusLost
        // TODO add your handling code here:
        if (jtNumPresenca.getText().isEmpty()) {
            jtNumPresenca.setBorder(BorderFactory.createLineBorder(Color.red));
            jlNumPresencaErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jtNumPresenca.setBorder(BorderFactory.createLineBorder(Color.green));
            jlNumPresencaErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jtNumPresencaFocusLost

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
        }// fecha if
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            jbLimpar.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jbLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpar();
        }// fecha if
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            jbRelatorio.grabFocus();
        }// fecha if
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            jbCadastrar.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jbLimparKeyPressed

    private void jbRelatorioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbRelatorioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            relatorio();
        }// fecha if
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            jbLimpar.grabFocus();
        }// fecha if
    }//GEN-LAST:event_jbRelatorioKeyPressed

    private void jrFemininoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jrFemininoFocusLost
        // TODO add your handling code here:
        if (!jrMasculino.isSelected() && !jrFeminino.isSelected()) {
            jlSexoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        } else {
            jlSexoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));

        }
    }//GEN-LAST:event_jrFemininoFocusLost

    private void cadastrar() {
        try {
            if (!jtNome.getText().isEmpty()) {
                a.setNome(jtNome.getText());
            } else {
                throw new NumberFormatException("Erro, nome em branco");
                
            }
            if (!jtIdade.getText().isEmpty()) {
                a.setIdade(Integer.parseInt(jtIdade.getText()));
            } else {
                throw new ArithmeticException("Erro, idade em branco");
            }
           
            if (!jtNota1.getText().isEmpty()) {
                a.setNota1(Double.parseDouble(jtNota1.getText()));
            } else {
                throw new ArithmeticException("Erro, Nota 1 em branco");
            }
            if (!jtNota2.getText().isEmpty()) {
                a.setNota2(Double.parseDouble(jtNota2.getText()));
            } else {
                throw new ArithmeticException("Erro, Nota 2 em branco");
            }
             if (!jtTotalAulas.getText().isEmpty()) {
                a.setTotalAulas(Integer.parseInt(jtTotalAulas.getText()));
            } else {
                throw new ArithmeticException("Erro, total de aulas em branco");
            }
            if (!jtPeso1.getText().isEmpty()) {
                a.setPeso1(Double.parseDouble(jtPeso1.getText()));
            } else {
                throw new ArithmeticException("Erro, Peso 1 em branco");
            }
            if (!jtPeso2.getText().isEmpty()) {
                a.setPeso2(Double.parseDouble(jtPeso2.getText()));
            } else {
                throw new ArithmeticException("Erro, Peso 2 em branco");
            }
            if (!jtNumPresenca.getText().isEmpty()) {
                a.setNumeroPresencas(Double.parseDouble(jtNumPresenca.getText()));
            } else {
                throw new ArithmeticException("Erro, número de presenças em branco");

            }
            if (!jrFeminino.isSelected() && !jrMasculino.isSelected()) {
                throw new Exception("Selecione o sexo");
            } else {
                a.setSexo(bgSexo.getSelection().getActionCommand());
            }
            a.setSexo(bgSexo.getSelection().getActionCommand());
            ArrayList<String> discCursadas = new ArrayList<>();
            if (jcAndroid.isSelected()) {
                discCursadas.add(jcAndroid.getText());
            }
            if (jcJava.isSelected()) {
                discCursadas.add(jcJava.getText());
            }
            if (jcPHP.isSelected()) {
                discCursadas.add(jcPHP.getText());
            }
            if (jcSO1.isSelected()) {
                discCursadas.add(jcSO1.getText());
            }
            a.setDiscCursadas(discCursadas);
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Aluno cadastrado com sucesso");

            jbRelatorio.setEnabled(true);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! " + e.getMessage());
        } catch (ArithmeticException e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! " + e.getMessage());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Algum erro ocorreu" + e.getMessage());
        } finally {
            System.out.println("Passou aqui!");
        }

    }

    private void limpar() {
        jtIdade.setText("");
        jtNome.setText("");
        jtNota1.setText("");
        jtNota2.setText("");
        jtNumPresenca.setText("");
        jtPeso1.setText("");
        jtPeso2.setText("");
        jtTotalAulas.setText("");
        bgSexo.clearSelection();
        jcAndroid.setSelected(false);
        jcJava.setSelected(false);
        jcPHP.setSelected(false);
        jcSO1.setSelected(false);
        jrMasculino.setSelected(true);
        jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtNome.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlIdadeErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtIdade.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlNota1Erro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtNota1.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlNota2Erro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtNota2.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlNumPresencaErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtNumPresenca.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlPeso1Erro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtPeso1.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlPeso2Erro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtPeso2.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jlSexoErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jlTotalAulasErro.setIcon(new ImageIcon(getClass().getResource("/")));
        jtTotalAulas.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }

    private void relatorio() {
        JOptionPane.showMessageDialog(
                rootPane,
                "Dados do aluno: " + a.toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICadAluno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UICadAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbRelatorio;
    private javax.swing.JCheckBox jcAndroid;
    private javax.swing.JCheckBox jcJava;
    private javax.swing.JCheckBox jcPHP;
    private javax.swing.JCheckBox jcSO1;
    private javax.swing.JLabel jlDiscCusr;
    private javax.swing.JLabel jlIdade;
    private javax.swing.JLabel jlIdadeErro;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlNota1;
    private javax.swing.JLabel jlNota1Erro;
    private javax.swing.JLabel jlNota2;
    private javax.swing.JLabel jlNota2Erro;
    private javax.swing.JLabel jlNumPresenca;
    private javax.swing.JLabel jlNumPresencaErro;
    private javax.swing.JLabel jlPeso1;
    private javax.swing.JLabel jlPeso1Erro;
    private javax.swing.JLabel jlPeso2;
    private javax.swing.JLabel jlPeso2Erro;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLabel jlSexoErro;
    private javax.swing.JLabel jlTotalAulas;
    private javax.swing.JLabel jlTotalAulasErro;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDiscCurs;
    private javax.swing.JLayeredPane jlpNotas;
    private javax.swing.JLayeredPane jlpTudo;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrMasculino;
    private javax.swing.JTextField jtIdade;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNota1;
    private javax.swing.JTextField jtNota2;
    private javax.swing.JTextField jtNumPresenca;
    private javax.swing.JTextField jtPeso1;
    private javax.swing.JTextField jtPeso2;
    private javax.swing.JTextField jtTotalAulas;
    // End of variables declaration//GEN-END:variables
}
